local M = {}

local config = require('hlcraft.config')
local dynamic_model = require('hlcraft.dynamic.model')
local codec = require('hlcraft.storage.codec')
local files = require('hlcraft.storage.files')

local function storage_dir()
  return config.config.persist_dir
end

--- Return the persisted override directory path.
--- @return string
function M.path()
  return storage_dir()
end

--- Return the persisted TOML file path for one top-level group.
--- @param group_name string|nil
--- @return string|nil
function M.file_path(group_name)
  return files.file_path(storage_dir(), group_name)
end

local function inflate_entries(data)
  local inflated_by_name = {}
  for name, entry in pairs(data.entries or {}) do
    local inflated = dynamic_model.inflate_entry(entry)
    data.entries[name] = inflated
    inflated_by_name[name] = inflated
  end

  for _, entries in pairs(data.sections or {}) do
    for name, entry in pairs(entries or {}) do
      entries[name] = inflated_by_name[name] or dynamic_model.inflate_entry(entry)
    end
  end

  return data
end

local function flatten_entries(entries)
  local flattened = {}
  for name, entry in pairs(entries or {}) do
    flattened[name] = dynamic_model.flatten_entry(entry)
  end
  return flattened
end

--- Load persisted highlight overrides from a directory of TOML files.
--- @param path string|nil
--- @return table
function M.load(path)
  local target = path or storage_dir()
  local stat = vim.uv.fs_stat(target)
  if not stat or stat.type ~= 'directory' then
    return codec.empty_data()
  end

  local data = codec.empty_data()
  for _, file in ipairs(files.toml_files_in_dir(target)) do
    codec.load_file(file, data)
  end

  return inflate_entries(data)
end

local function build_sections(overrides, groups)
  local sections = {}

  for highlight_name, entry in pairs(overrides or {}) do
    if entry and next(entry) ~= nil then
      local section_name = codec.normalize_group_name(groups and groups[highlight_name])
      if not section_name then
        return nil, ('Highlight %s must have a group before saving'):format(tostring(highlight_name))
      end
      sections[section_name] = sections[section_name] or {}
      sections[section_name][highlight_name] = entry
    end
  end

  for highlight_name, group_name in pairs(groups or {}) do
    local section_name = codec.normalize_group_name(group_name)
    if not section_name then
      return nil, ('Highlight %s must have a group before saving'):format(tostring(highlight_name))
    end
    sections[section_name] = sections[section_name] or {}
    sections[section_name][highlight_name] = sections[section_name][highlight_name]
      or (overrides and overrides[highlight_name])
      or {}
  end

  return sections, nil
end

--- Save persisted highlight overrides into one TOML file per top-level group.
--- @param overrides table
--- @param groups table|nil
--- @param path string|nil
--- @return boolean ok
--- @return string|nil err
function M.save(overrides, groups, path)
  local target = path or storage_dir()
  files.ensure_directory(target)

  local flattened_overrides = flatten_entries(overrides)
  local sections, section_err = build_sections(flattened_overrides, groups)
  if not sections then
    return false, section_err
  end

  local section_names = vim.tbl_keys(sections)
  table.sort(section_names)

  for _, section_name in ipairs(section_names) do
    local filepath = files.file_path(target, section_name)
    local lines = {
      '# Generated by hlcraft.nvim',
      '# Example: ["default"] then "Normal" = { fg = "#c8d3f5", bg = "NONE" }',
      '# Manual edits are preserved if they follow the grouped inline-table TOML shape.',
      '',
    }
    vim.list_extend(lines, codec.encode_section(section_name, sections[section_name]))

    local ok, err = files.atomic_write(filepath, lines)
    if not ok then
      return false, err
    end
  end

  files.remove_stale_toml_files(target, section_names)

  return true, nil
end

return M
