local M = {}

local config = require('hlcraft.config')
local highlight_names = require('hlcraft.core.highlight_names')
local tables = require('hlcraft.core.tables')
local codec = require('hlcraft.persistence.codec')
local files = require('hlcraft.persistence.files')
local schema = require('hlcraft.persistence.schema')

local function storage_dir()
  return config.config.persistence.dir
end

local function optional_path(path)
  if path == nil then
    return storage_dir()
  end
  if type(path) ~= 'string' or vim.trim(path) == '' then
    error('Persistence path must be a non-empty string', 3)
  end
  return path
end

local function highlight_name_error(name)
  local _, err = highlight_names.validate(name, 'Highlight name')
  return err
end

local function validate_save_inputs(overrides, groups)
  if type(overrides) ~= 'table' then
    return false, 'Overrides must be a table'
  end
  if type(groups) ~= 'table' then
    return false, 'Groups must be a table'
  end

  for highlight_name, entry in pairs(overrides) do
    local err = highlight_name_error(highlight_name)
    if err then
      return false, err
    end
    if type(entry) ~= 'table' then
      return false, ('Override entry %s must be a table'):format(highlight_name)
    end
  end

  for highlight_name, group_name in pairs(groups) do
    local err = highlight_name_error(highlight_name)
    if err then
      return false, err
    end
    if type(group_name) ~= 'string' then
      return false, ('Group for highlight %s must be a string'):format(highlight_name)
    end
    if not codec.normalize_group_name(group_name) then
      return false, ('Highlight %s must have a group before saving'):format(highlight_name)
    end
  end

  return true, nil
end

--- Return the persisted override directory path.
--- @return string
function M.path()
  return storage_dir()
end

--- Return the persisted TOML file path for one top-level group.
--- @param group_name string|nil
--- @return string|nil
function M.file_path(group_name)
  return files.file_path(storage_dir(), group_name)
end

--- Load persisted highlight overrides from a directory of TOML files.
--- @param path string|nil
--- @return table
function M.load(path)
  local target = optional_path(path)
  local stat = vim.uv.fs_stat(target)
  if not stat or stat.type ~= 'directory' then
    return codec.empty_data()
  end

  local data = codec.empty_data()
  local loaded_identities = {}
  for _, file in ipairs(files.toml_files_in_dir(target, { include_links = true })) do
    local identity = files.path_identity(file) or file
    if not loaded_identities[identity] then
      loaded_identities[identity] = true
      codec.load_file(file, data)
    end
  end

  return schema.normalize_loaded_data(data)
end

local function ensure_section(sections, section_name)
  if sections[section_name] == nil then
    sections[section_name] = {}
  end
  return sections[section_name]
end

local function section_entry(sections, section_name, highlight_name, override)
  local entries = ensure_section(sections, section_name)
  if entries[highlight_name] == nil then
    if override ~= nil then
      entries[highlight_name] = override
    else
      entries[highlight_name] = {}
    end
  end
end

local function build_sections(overrides, groups)
  local sections = {}

  for highlight_name, entry in pairs(overrides) do
    if next(entry) ~= nil then
      local group_name = groups[highlight_name]
      local section_name = codec.normalize_group_name(group_name)
      if not section_name then
        return nil, ('Highlight %s must have a group before saving'):format(highlight_name)
      end
      section_entry(sections, section_name, highlight_name, entry)
    end
  end

  for highlight_name, group_name in pairs(groups) do
    local section_name = codec.normalize_group_name(group_name)
    if not section_name then
      return nil, ('Highlight %s must have a group before saving'):format(highlight_name)
    end
    section_entry(sections, section_name, highlight_name, overrides[highlight_name])
  end

  return sections, nil
end

local function encoded_section_lines(section_name, entries)
  local lines = {
    '# Generated by hlcraft.nvim',
    '# Example: ["default"] then "Normal" = { fg = "#c8d3f5", bg = "NONE" }',
    '# Manual edits are preserved if they follow the grouped inline-table TOML shape.',
    '',
  }
  vim.list_extend(lines, codec.encode_section(section_name, entries))
  return lines
end

local function cleanup_temp_files(writes)
  local errors = {}
  for _, write in ipairs(writes) do
    if write.temp_path then
      local removed, err = files.remove_temp(write.temp_path)
      if removed then
        write.temp_path = nil
      else
        errors[#errors + 1] = err
      end
    end
  end
  return errors
end

local function commit_backup_paths(commits)
  local paths = {}
  for _, commit in ipairs(commits) do
    if commit.backup then
      paths[#paths + 1] = commit.backup
    end
  end
  return paths
end

local function write_filepaths(writes)
  local paths = {}
  for _, write in ipairs(writes) do
    paths[#paths + 1] = write.filepath
  end
  return paths
end

local function append_paths(paths, extra_paths)
  for _, path in ipairs(extra_paths) do
    paths[#paths + 1] = path
  end
  return paths
end

local function restore_commit(commit)
  if commit.existed then
    os.remove(commit.filepath)
    local ok, err = os.rename(commit.backup, commit.filepath)
    if not ok then
      return false, ('Failed to restore TOML file %s: %s'):format(commit.filepath, tostring(err))
    end
    return true, nil
  end

  local ok, err = os.remove(commit.filepath)
  if not ok and vim.uv.fs_lstat(commit.filepath) then
    return false, ('Failed to remove TOML file %s: %s'):format(commit.filepath, tostring(err))
  end
  return true, nil
end

local function rollback_commits(commits)
  local errors = {}
  for index = #commits, 1, -1 do
    local ok, err = restore_commit(commits[index])
    if not ok then
      errors[#errors + 1] = err
    end
  end
  return errors
end

local function rollback_save(commits, stale_backups)
  local errors = {}
  if stale_backups then
    vim.list_extend(errors, files.rollback_stale_toml_backups(stale_backups))
  end
  vim.list_extend(errors, rollback_commits(commits))
  return errors
end

local function append_rollback_errors(err, rollback_errors)
  if #rollback_errors == 0 then
    return err
  end
  return ('%s; rollback errors: %s'):format(err, table.concat(rollback_errors, '; '))
end

local function with_save_lock(target, callback)
  local acquired, lock_or_err = files.acquire_save_lock(target)
  if not acquired then
    return false, lock_or_err
  end

  local call_ok, ok, err = xpcall(callback, debug.traceback)
  local released, release_err = files.release_save_lock(lock_or_err)
  if not call_ok then
    if not released then
      error(append_rollback_errors(ok, { release_err }), 0)
    end
    error(ok, 0)
  end
  if not released then
    if ok == false then
      err = append_rollback_errors(err, { release_err })
    else
      return false, release_err
    end
  end
  return ok, err
end

local function backup_path(filepath)
  return filepath .. '.bak'
end

local function prepare_commit(filepath)
  local backup = backup_path(filepath)
  local existing = vim.uv.fs_lstat(filepath)
  if not existing then
    return true, {
      filepath = filepath,
      existed = false,
    }
  end

  if vim.uv.fs_lstat(backup) then
    return false, ('Cannot back up TOML file %s: backup already exists'):format(filepath)
  end

  local ok, err = os.rename(filepath, backup)
  if not ok then
    return false, ('Failed to back up TOML file %s: %s'):format(filepath, tostring(err))
  end

  return true, {
    filepath = filepath,
    backup = backup,
    existed = true,
  }
end

local function commit_temp_files(writes)
  local commits = {}
  for _, write in ipairs(writes) do
    local prepared, commit_or_err = prepare_commit(write.filepath)
    if not prepared then
      local rollback_errors = cleanup_temp_files(writes)
      vim.list_extend(rollback_errors, rollback_commits(commits))
      return false, append_rollback_errors(commit_or_err, rollback_errors)
    end

    local commit = commit_or_err
    local ok, err = files.commit_temp(write.filepath, write.temp_path)
    if not ok then
      local rollback_errors = {}
      local restored, restore_err = restore_commit(commit)
      if not restored then
        rollback_errors[#rollback_errors + 1] = restore_err
      end
      vim.list_extend(rollback_errors, rollback_commits(commits))
      vim.list_extend(rollback_errors, cleanup_temp_files(writes))
      return false, append_rollback_errors(err, rollback_errors)
    end

    write.temp_path = nil
    commits[#commits + 1] = commit
  end

  return true, commits
end

local function save_sections(target, section_names, sections)
  local writes = {}
  local write_paths = {}
  for _, section_name in ipairs(section_names) do
    local filepath = files.file_path(target, section_name)
    local recovered, recover_err = files.recover_write_backup(filepath)
    if not recovered then
      return false, recover_err
    end
    local write_path, write_path_err = files.write_target_path(filepath)
    if not write_path then
      return false, write_path_err
    end
    if write_paths[write_path] then
      return false,
        ('Multiple TOML sections resolve to the same file: %s and %s'):format(write_paths[write_path], section_name)
    end
    write_paths[write_path] = section_name
    local target_ok, target_err = files.validate_write_target(write_path)
    if not target_ok then
      return false, target_err
    end
    writes[#writes + 1] = {
      filepath = write_path,
      lines = encoded_section_lines(section_name, sections[section_name]),
    }
  end

  for _, write in ipairs(writes) do
    local ok, temp_or_err = files.write_temp(write.filepath, write.lines)
    if not ok then
      return false, append_rollback_errors(temp_or_err, cleanup_temp_files(writes))
    end
    write.temp_path = temp_or_err
  end

  local commit_ok, commits_or_err = commit_temp_files(writes)
  if not commit_ok then
    return false, commits_or_err
  end
  local commits = commits_or_err

  local stale_ok, stale_backups_or_err = files.remove_stale_toml_files(target, section_names, {
    protected_paths = write_filepaths(writes),
    defer_backup_finalization = true,
  })
  if not stale_ok then
    return false, append_rollback_errors(stale_backups_or_err, rollback_commits(commits))
  end
  local stale_backups = stale_backups_or_err

  local backup_paths = append_paths(commit_backup_paths(commits), files.stale_toml_backup_paths(stale_backups))
  local finalized, finalize_err = files.finalize_backup_paths(backup_paths, 'TOML backup')
  if not finalized then
    return false, append_rollback_errors(finalize_err, rollback_save(commits, stale_backups))
  end
  return true, nil
end

--- Save persisted highlight overrides into one TOML file per top-level group.
--- @param overrides table
--- @param groups table
--- @param path string|nil
--- @return boolean ok
--- @return string|nil err
function M.save(overrides, groups, path)
  local target = optional_path(path)

  local valid, validation_err = validate_save_inputs(overrides, groups)
  if not valid then
    return false, validation_err
  end

  local normalized_overrides, normalize_err = schema.normalize_entries(overrides)
  if not normalized_overrides then
    return false, normalize_err
  end

  local sections, section_err = build_sections(normalized_overrides, groups)
  if not sections then
    return false, section_err
  end

  local section_names = tables.sorted_keys(sections)
  local dir_ok, dir_err = files.ensure_directory(target)
  if not dir_ok then
    return false, dir_err
  end

  return with_save_lock(target, function()
    return save_sections(target, section_names, sections)
  end)
end

return M
