local M = {}

local config = require('hlcraft.config')
local tables = require('hlcraft.core.tables')
local codec = require('hlcraft.persistence.codec')
local files = require('hlcraft.persistence.files')
local schema = require('hlcraft.persistence.schema')

local function storage_dir()
  return config.config.persist_dir
end

local function optional_path(path)
  if path == nil then
    return storage_dir()
  end
  if type(path) ~= 'string' then
    error('Persistence path must be a string', 3)
  end
  return path
end

local function highlight_name_is_valid(name)
  return type(name) == 'string' and vim.trim(name) ~= ''
end

local function validate_save_inputs(overrides, groups)
  if type(overrides) ~= 'table' then
    return false, 'Overrides must be a table'
  end
  if type(groups) ~= 'table' then
    return false, 'Groups must be a table'
  end

  for highlight_name, entry in pairs(overrides) do
    if not highlight_name_is_valid(highlight_name) then
      return false, 'Highlight name must be a non-empty string'
    end
    if type(entry) ~= 'table' then
      return false, ('Override entry %s must be a table'):format(highlight_name)
    end
  end

  for highlight_name, group_name in pairs(groups) do
    if not highlight_name_is_valid(highlight_name) then
      return false, 'Highlight name must be a non-empty string'
    end
    if type(group_name) ~= 'string' then
      return false, ('Group for highlight %s must be a string'):format(highlight_name)
    end
    if not codec.normalize_group_name(group_name) then
      return false, ('Highlight %s must have a group before saving'):format(highlight_name)
    end
  end

  return true, nil
end

--- Return the persisted override directory path.
--- @return string
function M.path()
  return storage_dir()
end

--- Return the persisted TOML file path for one top-level group.
--- @param group_name string|nil
--- @return string|nil
function M.file_path(group_name)
  return files.file_path(storage_dir(), group_name)
end

--- Load persisted highlight overrides from a directory of TOML files.
--- @param path string|nil
--- @return table
function M.load(path)
  local target = optional_path(path)
  local stat = vim.uv.fs_stat(target)
  if not stat or stat.type ~= 'directory' then
    return codec.empty_data()
  end

  local data = codec.empty_data()
  for _, file in ipairs(files.toml_files_in_dir(target, { include_links = true })) do
    codec.load_file(file, data)
  end

  return schema.normalize_loaded_data(data)
end

local function ensure_section(sections, section_name)
  if sections[section_name] == nil then
    sections[section_name] = {}
  end
  return sections[section_name]
end

local function section_entry(sections, section_name, highlight_name, override)
  local entries = ensure_section(sections, section_name)
  if entries[highlight_name] == nil then
    if override ~= nil then
      entries[highlight_name] = override
    else
      entries[highlight_name] = {}
    end
  end
end

local function build_sections(overrides, groups)
  local sections = {}

  for highlight_name, entry in pairs(overrides) do
    if next(entry) ~= nil then
      local group_name = groups[highlight_name]
      local section_name = codec.normalize_group_name(group_name)
      if not section_name then
        return nil, ('Highlight %s must have a group before saving'):format(highlight_name)
      end
      section_entry(sections, section_name, highlight_name, entry)
    end
  end

  for highlight_name, group_name in pairs(groups) do
    local section_name = codec.normalize_group_name(group_name)
    if not section_name then
      return nil, ('Highlight %s must have a group before saving'):format(highlight_name)
    end
    section_entry(sections, section_name, highlight_name, overrides[highlight_name])
  end

  return sections, nil
end

--- Save persisted highlight overrides into one TOML file per top-level group.
--- @param overrides table
--- @param groups table
--- @param path string|nil
--- @return boolean ok
--- @return string|nil err
function M.save(overrides, groups, path)
  local target = path or storage_dir()

  local valid, validation_err = validate_save_inputs(overrides, groups)
  if not valid then
    return false, validation_err
  end

  files.ensure_directory(target)

  local normalized_overrides, normalize_err = schema.normalize_entries(overrides)
  if not normalized_overrides then
    return false, normalize_err
  end

  local sections, section_err = build_sections(normalized_overrides, groups)
  if not sections then
    return false, section_err
  end

  local section_names = tables.sorted_keys(sections)

  for _, section_name in ipairs(section_names) do
    local filepath = files.file_path(target, section_name)
    local lines = {
      '# Generated by hlcraft.nvim',
      '# Example: ["default"] then "Normal" = { fg = "#c8d3f5", bg = "NONE" }',
      '# Manual edits are preserved if they follow the grouped inline-table TOML shape.',
      '',
    }
    vim.list_extend(lines, codec.encode_section(section_name, sections[section_name]))

    local ok, err = files.atomic_write(filepath, lines)
    if not ok then
      return false, err
    end
  end

  files.remove_stale_toml_files(target, section_names)

  return true, nil
end

return M
